using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace SomeEngine.Generators;

/// <summary>
/// 扫描所有带 [MaterialTag("name")] 特性的 struct，
/// 生成静态 MaterialTagResolver.Resolve(string) → Action 映射。
/// 无反射、无字典查找。
/// </summary>
[Generator]
public class MaterialTagDeserializerGenerator : IIncrementalGenerator
{
    private const string MaterialTagAttr = "SomeEngine.Render.Materials.MaterialTagAttribute";
    private const string IMaterialTagType = "SomeEngine.Render.Materials.IMaterialTag";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var tagTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is StructDeclarationSyntax sds &&
                    sds.AttributeLists.Count > 0,
                transform: static (ctx, _) => GetTagInfo(ctx))
            .Where(static info => info is not null)
            .Select(static (info, _) => info!.Value)
            .Collect();

        context.RegisterSourceOutput(tagTypes, static (spc, tags) =>
        {
            if (tags.Length == 0) return;
            var source = GenerateResolver(tags);
            spc.AddSource("MaterialTagResolver.g.cs", source);
        });
    }

    private static TagInfo? GetTagInfo(GeneratorSyntaxContext ctx)
    {
        var structDecl = (StructDeclarationSyntax)ctx.Node;
        if (ctx.SemanticModel.GetDeclaredSymbol(structDecl) is not INamedTypeSymbol symbol)
            return null;

        // Must implement IMaterialTag
        bool implementsTag = symbol.AllInterfaces.Any(i => i.ToDisplayString() == IMaterialTagType);
        if (!implementsTag)
            return null;

        // Must have [MaterialTag("...")] attribute
        foreach (var attr in symbol.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != MaterialTagAttr)
                continue;

            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string name)
            {
                return new TagInfo(
                    symbol.ContainingNamespace.ToDisplayString(),
                    symbol.Name,
                    name
                );
            }
        }

        return null;
    }

    private static string GenerateResolver(ImmutableArray<TagInfo> tags)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using SomeEngine.Render.Materials;");
        sb.AppendLine();
        sb.AppendLine("namespace SomeEngine.Render.Materials;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Auto-generated tag resolver. Maps serialization names to IMaterialTag types.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class MaterialTagResolver");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Applies a named tag to a MaterialPass via the registry.");
        sb.AppendLine("    /// Returns true if the tag name was recognized.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static bool ApplyTag(MaterialRegistry registry, MaterialPass pass, string tagName, int value = 0)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (tagName)");
        sb.AppendLine("        {");

        foreach (var tag in tags)
        {
            var fullTypeName = $"{tag.Namespace}.{tag.TypeName}";
            sb.AppendLine($"            case \"{tag.SerializationName}\":");
            sb.AppendLine($"                registry.SetTag(pass, default({fullTypeName}));");
            sb.AppendLine($"                return true;");
        }

        sb.AppendLine("            default:");
        sb.AppendLine("                return false;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private readonly struct TagInfo
    {
        public readonly string Namespace;
        public readonly string TypeName;
        public readonly string SerializationName;

        public TagInfo(string ns, string typeName, string serializationName)
        {
            Namespace = ns;
            TypeName = typeName;
            SerializationName = serializationName;
        }
    }
}
