<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\SomeJob\src\SomeJob\SomeJob.csproj" />
    <ProjectReference Include="..\..\..\SomeECS\src\SomeECS.Core\SomeECS.Core.csproj" />
    <ProjectReference Include="..\..\..\SomeECS\src\SomeECS.Systems\SomeECS.Systems.csproj" />
  </ItemGroup>
</Project>
