<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SomeEngine.Render\SomeEngine.Render.csproj" />
    <ProjectReference Include="..\SomeEngine.Core\SomeEngine.Core.csproj" />
    <ProjectReference Include="..\SomeEngine.Assets\SomeEngine.Assets.csproj" />
    <ProjectReference Include="..\SomeEngine.Rhi\SomeEngine.Rhi.csproj" />
    <ProjectReference Include="..\SomeEngine.Rhi.D3D12\SomeEngine.Rhi.D3D12.csproj" />
    <ProjectReference Include="..\..\..\SomeECS\src\SomeECS.Core\SomeECS.Core.csproj" />
    <ProjectReference Include="..\..\..\SomeECS\src\SomeECS.Systems\SomeECS.Systems.csproj" />
  </ItemGroup>
</Project>
