<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SomeEngine.Rhi\SomeEngine.Rhi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
  </ItemGroup>

</Project>
